syncfusion-content/typescript-docs

TypeScript/Diagram/Getting-Started.md, TypeScript/Grid/Editing.md, TypeScript/Menu/Separators.md, TypeScript/PdfViewer/getting-started.md
Hi @ChristoIssac,
Worked on Bing report issues, merge these changes.
Regards,
Gowthaman
=> SEO-1973_Site_Audit_Issues

TypeScript/Grid/Data-Binding.md, TypeScript/Grid/Filter.md, TypeScript/Menu/Getting-Started.md, TypeScript/Toolbar/Responsive-Layout.md
Hi @ChristoIssac,
Worked on Site Audit Bing report issues, merge these changes.
Regards,
Gowthaman
=> SEO-2050_Site_Audit_Issues

TypeScript/Menu/Data-binding.md, TypeScript/RangeNavigator/Globalization-And-Localization.md
Worked on Site audit issues, merge these changes.
Regards,
Gowthaman
=> SEO-2245_Site_Audit_Issues

TypeScript/DropDownList/HowTo.md
Worked on site audit issues, merge these changes.
Regards,
Gowthaman
=> SEO-2344_Site_Audit_Issues

TypeScript/Chart/Chart-Dimensions.md, TypeScript/Ribbon/Tab.md, TypeScript/TreeMap/Getting-Started.md
Worked on Site Audit issues, so merge these changes,
Regards,
Gowthaman
=> SEO-2423_Site_Audit_Issues

TypeScript/Button/Icons.md, TypeScript/Ribbon/Screen-Tips.md
Worked on site audit issues, merge these changes,
Regards,
Gowthaman
=> SEO-2475_Site_Audit_Issues

TypeScript/Tooltip/HowTo.md
|Title|Description|
|:--|:--|
|**Task Category** | Need to rename 4 image - Alt Text|
|**Content task link/ Mail screenshot** | N/A |
|**Hotfix PR link** | https://github.com/syncfusion-content/typescript-docs/pull/161
|**Ticket link/Task link** | https://syncfusion.atlassian.net/browse/SEO-2705 |
|**Excel/SharePoint link** | N/A |
=> SEO-2750 - Typescript Tooltip image renamed

TypeScript/Grid/Columns.md, TypeScript/ProgressBar/Getting-Started.md
Please review image alt text changes for TypeScript controls.
Regards,
Sharly A.
=> SEO-2971 - Typescript Control image alt text changes

TypeScript/NuGet-Packages.md
Please review http to https changes.
Regards,
Sharly A.
=> SEO-3108 - Typescript http to https

TypeScript/CircularGauge/Indicators.md, TypeScript/ToggleButton/getting-started.md
Hi @Aishwarya-Ganesan ,
Please review the changes for TypeScript Desc too long short.
Regards,
Yvone.
=> SEO-3147 TypeScript Desc too long short

TypeScript/NavigationDrawer/overview.md, TypeScript/RadialMenu/getting-started.md, TypeScript/Tab/Getting-Started.md, TypeScript/ToggleButton/getting-started.md
Worked on bing report issues, so merge these changes
Regards,
Gowthaman
=> SEO-3261-bing-report-issues

TypeScript/Gantt/Getting-Started.md
Renamed image alt text.
Regards,
Sharly A.
=> SEO-3353 - Typescript controls image alt text

TypeScript/NavigationDrawer/customize-direction.md, TypeScript/TreeMap/Getting-Started.md, TypeScript/TreeMap/Layout.md
Worked on SEMrush report issues, so merge these changes
Regards,
Gowthaman
=> SEO-3439-semrush-report-issues

TypeScript/Autocomplete/multicolumn.md, TypeScript/Autocomplete/template.md, TypeScript/Scroller/Getting-Started.md
Worked on Bing report issues, so merge these changes
Regards,
Gowthaman
=> SEO-3615-bing-issues

TypeScript/DropDownList/Accessibility.md, TypeScript/DropDownList/Customization.md, TypeScript/DropDownList/DataBinding.md, TypeScript/DropDownList/Functionalities.md, TypeScript/DropDownList/Getting-Started.md, TypeScript/DropDownList/HowTo.md, TypeScript/DropDownList/Rendering-Mode.md, TypeScript/FileExplorer/Overview.md, TypeScript/FileExplorer/Toolbar.md, TypeScript/FileExplorer/getting-started.md, TypeScript/Grid/Data-Binding.md, TypeScript/Grid/Editing.md, TypeScript/Grid/Getting-Started.md, TypeScript/Kanban/Data-Binding.md, TypeScript/Kanban/Getting-Started.md, TypeScript/Kanban/Overview.md, TypeScript/Kanban/Styling.md
Hi @Girija-Rajendran,
Worked on redirection-related fixes, so merge these changes,
Regards,
Gowthaman
=> SEO-172685-TypeSccript-redirection-tool-fixes-1

TypeScript/NuGet-Packages.md, TypeScript/Schedule/Dependencies.md, TypeScript/Schedule/Getting-Started.md, TypeScript/Schedule/data-binding.md, TypeScript/Schedule/recurrence-editor.md, TypeScript/Schedule/working-with-appointments.md, TypeScript/Spreadsheet/Getting-Started.md, TypeScript/TimePicker/Keyboard-Interaction.md, TypeScript/Tooltip/Customization.md, TypeScript/Tooltip/Getting-Started.md, TypeScript/TreeMap/Angular-Support.md, TypeScript/TreeMap/Customization.md, TypeScript/TreeMap/Drill-Down-Support.md, TypeScript/TreeMap/Layout.md, TypeScript/TreeMap/TreeMap-Elements.md, TypeScript/TreeMap/TreeMapLevels.md, TypeScript/TreeView/Drag-and-Drop.md, TypeScript/TreeView/Full-Row-Selection.md, TypeScript/TreeView/How-To.md, TypeScript/TreeView/Keyboard-Interaction.md, TypeScript/TreeView/Multiple-Drag-and-Drop.md, TypeScript/TreeView/Multiple-Selection.md, TypeScript/TreeView/Overview.md, TypeScript/TreeView/Populate-Data.md, TypeScript/TreeView/Template-Support.md, TypeScript/TreeView/Tree-Node.md
Hi @Girija-Rajendran,
Worked on redirection-related fixes, so merge these changes,
Regards,
Gowthaman
=> SEO-172685-TypeSccript-redirection-tool-fixes-3

TypeScript/TimePicker/Getting-Started.md
Hi @MallikaRK,
Worked on description too long / short.
Regards,
Sharly A.
=> SEO-172159 - TypeScript Description too long/short

TypeScript/Chart/Chart-Title.md, TypeScript/Chart/Chart-Types.md
Hi @Aishwarya-Ganesan
Corrected the page not found links in this help page. Please check and merge the same.
Thanks,
Mallika
=> SEO-175881: Page Not Found UG link - fix

TypeScript/BulletGraph/Getting-Started.md, TypeScript/Diagram/Getting-Started.md, TypeScript/Kanban/Styling.md
Hi @MallikaRK,
Worked on redirection links. Please review.
Regards,
Sharly A.
=> SEO-175684 - Typescript changes

TypeScript/Chart/Axis.md, TypeScript/Chart/Chart-Dimensions.md, TypeScript/Chart/Chart-Series.md, TypeScript/Chart/Chart-Title.md, TypeScript/Chart/Chart-Types.md, TypeScript/Chart/Data-Markers.md, TypeScript/Chart/Empty-Points.md, TypeScript/Chart/Legend.md, TypeScript/Chart/Multiple-Panes.md, TypeScript/Chart/Working-with-Data.md
Hi @Aishwarya-Ganesan ,
Please review changes for TypeScript Chart broken links.
Regards,
Selline Rita.
=> SEO-175689-TypeScript-Chart-Issues

TypeScript/CircularGauge/Getting-Started.md, TypeScript/DatePicker/How-To.md, TypeScript/DatePicker/Validation.md
Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.
Regards,
Edith.
=> SEO-176062-Typscript--control-issue-fixes

TypeScript/RichTextEditor/Getting-Started.md, TypeScript/RichTextEditor/Image-and-File-browser.md, TypeScript/RichTextEditor/Validation.md
Please review the changes made.
Regards
Scholar.
=> SEO-175234-TypeScript-docs

TypeScript/Schedule/customization.md, TypeScript/Schedule/data-binding.md, TypeScript/Schedule/recurrence-editor.md
Hello,
I have worked on the links with redirects 
Regards,
Beryl.
=> SEO-175653-Scheduler-Links-With-Redirects

TypeScript/CheckBox/Easy-customization.md, TypeScript/FileExplorer/Accessing-Shared-Folder.md
Hello,
I have worked on the image alt text.
Regards,
Beryl.
=> SEO-176113-Image-Alt-Text-Typescript
